version: 4.0.0

navbar:
  menu:
    主页: /
    文档: /posts
    标签: /tags
    关于: /about

article:
  highlight:
    theme: monokai
    clipboard: true
    fold: unfolded

providers:
    iconcdn: 'https://cdn.bootcdn.net/ajax/libs/font-awesome/5.13.1/css/all.css'
